from . import fulfillment_box  # noqa: F401
from . import fulfillment_shipment  # noqa: F401
from . import fulfillment_shipment_group  # noqa: F401
from . import print_job  # noqa: F401
from . import print_test_wizard  # noqa: F401
from . import shopify_order  # noqa: F401
from . import shopify_order_line  # noqa: F401
from . import shopify_config_wizard  # noqa: F401
from . import project_task  # noqa: F401
from . import res_config_settings  # noqa: F401
from . import res_partner  # noqa: F401
