import logging
from odoo import api, fields, models, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

class ProjectTask(models.Model):
    _inherit = "project.task"

    shopify_order_id = fields.Many2one("shopify.order", string="Shopify Order", readonly=True)
    is_fulfillment_task = fields.Boolean(string="Is Fulfillment Task", default=False)
    fulfillment_inventory_deducted = fields.Boolean(string="Inventory Deducted", default=False, readonly=True)
    fulfillment_restock_item_id = fields.Many2one(
        "fulfillment.restock.item",
        string="POS Restock Item",
        ondelete="set null",
    )

    @staticmethod
    def _is_done_state(state):
        return isinstance(state, str) and state.endswith("done")

    def _restock_task_is_done(self) -> bool:
        """Mirror the original restock plugin's done check (Odoo 18 state -> stage fallback)."""
        self.ensure_one()
        if "state" in self._fields and self.state:
            return self.state == "1_done"
        stage = self.stage_id
        if not stage:
            return False
        if "is_closed" in stage._fields:
            return bool(stage.is_closed)
        if "fold" in stage._fields:
            return bool(stage.fold)
        return False

    def _send_task_error_alert(self, title: str, message: str):
        self.ensure_one()
        try:
            from odoo.addons.shopify_fulfillment.services.alert_service import AlertService

            AlertService.from_env(self.env).notify_error(
                title=title,
                message=message,
                order=self.shopify_order_id if self.shopify_order_id else None,
                extra={
                    "task_id": str(self.id),
                    "task_name": self.name or "",
                },
            )
        except Exception:
            _logger.exception("Task %s: failed to send task error alert", self.id)

    def _get_sale_order_delivery(self, sale_order):
        """Return the open delivery generated by the sale order."""
        self.ensure_one()
        pickings = sale_order.picking_ids.filtered(
            lambda p: p.picking_type_code == "outgoing" and p.state not in ("cancel", "done")
        )
        if pickings:
            return pickings.sorted(lambda p: (p.scheduled_date or p.create_date, p.id))[0]

        done_pickings = sale_order.picking_ids.filtered(
            lambda p: p.picking_type_code == "outgoing" and p.state == "done"
        )
        if done_pickings:
            return done_pickings.sorted(lambda p: (p.date_done or p.create_date, p.id))[-1]

        raise UserError(_("No delivery order was generated for Sale Order %s.") % sale_order.name)

    def _set_picking_done_quantities(self, picking):
        """Mark every sale-order delivery move as fully picked for Odoo 18."""
        for move in picking.move_ids.filtered(lambda m: m.state not in ("cancel", "done")):
            qty_done = move.product_uom_qty or 0.0
            if hasattr(move, "quantity"):
                move.quantity = qty_done
            if hasattr(move, "quantity_done"):
                move.quantity_done = qty_done

            for move_line in move.move_line_ids:
                if hasattr(move_line, "qty_done"):
                    move_line.qty_done = qty_done
                elif hasattr(move_line, "quantity_done"):
                    move_line.quantity_done = qty_done
                elif hasattr(move_line, "quantity"):
                    move_line.quantity = qty_done

            if hasattr(move, "picked"):
                move.picked = True

    def _mark_sale_order_paid(self, sale_order):
        """Create/post the customer invoice and register payment for paid online orders."""
        self.ensure_one()

        invoices = sale_order.invoice_ids.filtered(
            lambda move: move.move_type == "out_invoice" and move.state != "cancel"
        )
        if sale_order.invoice_status != "invoiced":
            invoices |= sale_order._create_invoices(final=True)

        invoices = invoices.filtered(lambda move: move.move_type == "out_invoice" and move.state != "cancel")
        if not invoices:
            raise UserError(_("No invoice could be created for Sale Order %s.") % sale_order.name)

        for invoice in invoices:
            if invoice.state == "draft":
                invoice.action_post()

        unpaid_invoices = invoices.filtered(
            lambda move: move.payment_state not in ("paid", "in_payment", "reversed")
            and move.amount_residual > 0
        )
        if not unpaid_invoices:
            return invoices

        journal = self.env["account.journal"].search(
            [
                ("type", "=", "bank"),
                ("company_id", "=", sale_order.company_id.id),
                ("active", "=", True),
            ],
            limit=1,
        )
        if not journal:
            journal = self.env["account.journal"].search(
                [
                    ("type", "=", "cash"),
                    ("company_id", "=", sale_order.company_id.id),
                    ("active", "=", True),
                ],
                limit=1,
            )
        if not journal:
            raise UserError(_("No active Bank or Cash journal found to mark %s paid.") % sale_order.name)

        register = self.env["account.payment.register"].with_context(
            active_model="account.move",
            active_ids=unpaid_invoices.ids,
        ).create({
            "journal_id": journal.id,
            "payment_date": fields.Date.context_today(self),
        })
        register.action_create_payments()
        return invoices

    def action_fulfillment_deduct_inventory(self):
        """Deduct inventory for the linked Shopify Order."""
        self.ensure_one()
        if not self.shopify_order_id or not self.is_fulfillment_task:
            return
            
        if self.fulfillment_inventory_deducted:
            return

        try:
            risk_level = self.shopify_order_id._refresh_shopify_risk_level()
        except UserError as exc:
            message = str(exc)
            self.shopify_order_id.write({
                "state": "manual_required",
                "error_message": message,
            })
            self.message_post(body=message)
            return

        if risk_level in ("HIGH", "MEDIUM"):
            message = _(
                "Inventory deduction stopped because Shopify marked this order as %s risk. "
                "Manual review is required before fulfillment."
            ) % risk_level.title()
            self.shopify_order_id.write({
                "state": "manual_required",
                "error_message": message,
            })
            self.shopify_order_id._send_risk_notification()
            self.message_post(body=message)
            return

        _logger.info("Starting inventory deduction for task %s (Order: %s)", self.id, self.shopify_order_id.order_name)

        try:
            sale_order = self.shopify_order_id._create_sale_order()
            if not sale_order:
                raise UserError(_("Sale order could not be created for %s.") % self.shopify_order_id.order_name)

            picking = self._get_sale_order_delivery(sale_order)
            if picking.state != "done":
                if picking.state == "draft":
                    picking.action_confirm()
                picking.action_assign()
                self._set_picking_done_quantities(picking)
                picking.button_validate()

            invoices = self._mark_sale_order_paid(sale_order)
            self.fulfillment_inventory_deducted = True
            invoice_names = ", ".join(invoices.mapped("name"))
            self.message_post(
                body=_("Sale Order %s delivered via %s and marked paid (%s).")
                % (sale_order.name, picking.name, invoice_names)
            )
            _logger.info(
                "Order %s delivered through Sale Order %s, Delivery %s, Invoices %s",
                self.shopify_order_id.order_name,
                sale_order.name,
                picking.name,
                invoice_names,
            )
                
        except Exception as e:
            _logger.exception("Failed to fulfill sale order for task %s", self.id)
            self.message_post(body=_("Failed to fulfill sale order: %s") % str(e))
            self._send_task_error_alert("Sale Order Fulfillment Failed", str(e))


    @api.model_create_multi
    def create(self, vals_list):
        tasks = super().create(vals_list)
        for task in tasks:
            if task.is_fulfillment_task and self._is_done_state(task.state) and not task.fulfillment_inventory_deducted:
                try:
                    task.action_fulfillment_deduct_inventory()
                except Exception as e:
                    _logger.exception("Error in auto-deduct inventory on create")
                    task.message_post(body=_("Background error during inventory deduction: %s") % str(e))
                    task._send_task_error_alert("Inventory Auto-Deduct Failed (Create)", str(e))
        return tasks

    def write(self, vals):
        restock_tasks = self.filtered("fulfillment_restock_item_id")
        restock_done_before = {t.id: t._restock_task_is_done() for t in restock_tasks}

        res = super().write(vals)
        # Check if task is being marked as done
        if 'state' in vals and self._is_done_state(vals["state"]):
             for task in self:
                  if task.is_fulfillment_task and not task.fulfillment_inventory_deducted:
                      try:
                          task.action_fulfillment_deduct_inventory()
                      except Exception as e:
                          # Don't block the write
                          _logger.exception("Error in auto-deduct inventory on write")
                          task.message_post(body=_("Background error during inventory deduction: %s") % str(e))
                          task._send_task_error_alert("Inventory Auto-Deduct Failed (Write)", str(e))

        for task in restock_tasks:
            try:
                if restock_done_before.get(task.id):
                    continue
                if not task._restock_task_is_done():
                    continue
                items = self.env["fulfillment.restock.item"].sudo().search([
                    ("todo_task_id", "=", task.id),
                    ("is_active_snapshot", "=", True),
                    ("inventory_transferred", "=", False),
                ])
                if (
                    not items
                    and task.fulfillment_restock_item_id
                    and task.fulfillment_restock_item_id.is_active_snapshot
                    and not task.fulfillment_restock_item_id.inventory_transferred
                ):
                    items = task.fulfillment_restock_item_id
                if not items:
                    continue
                _logger.info(
                    "Restock task %s marked done; transferring inventory for items %s",
                    task.id, items.ids,
                )
                items.with_context(
                    transferred_by_uid=self.env.user.id
                ).sudo().action_transfer_inventory()
            except Exception:  # pylint: disable=broad-except
                _logger.exception(
                    "Failed to auto-transfer inventory for restock task %s", task.id
                )

        return res
