import logging
from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError
from odoo.tools import float_compare

_logger = logging.getLogger(__name__)

class ProjectTask(models.Model):
    _inherit = "project.task"

    shopify_order_id = fields.Many2one("shopify.order", string="Shopify Order", readonly=True)
    is_fulfillment_task = fields.Boolean(string="Is Fulfillment Task", default=False)
    fulfillment_inventory_deducted = fields.Boolean(string="Inventory Deducted", default=False, readonly=True)
    fulfillment_restock_item_id = fields.Many2one(
        "fulfillment.restock.item",
        string="POS Restock Item",
        ondelete="set null",
    )

    @staticmethod
    def _is_done_state(state):
        return isinstance(state, str) and state.endswith("done")

    def _restock_task_is_done(self) -> bool:
        """Mirror the original restock plugin's done check (Odoo 18 state -> stage fallback)."""
        self.ensure_one()
        if "state" in self._fields and self.state:
            return self.state == "1_done"
        stage = self.stage_id
        if not stage:
            return False
        if "is_closed" in stage._fields:
            return bool(stage.is_closed)
        if "fold" in stage._fields:
            return bool(stage.fold)
        return False

    def _send_task_error_alert(self, title: str, message: str):
        self.ensure_one()
        try:
            from odoo.addons.shopify_fulfillment.services.alert_service import AlertService

            AlertService.from_env(self.env).notify_error(
                title=title,
                message=message,
                order=self.shopify_order_id if self.shopify_order_id else None,
                extra={
                    "task_id": str(self.id),
                    "task_name": self.name or "",
                },
            )
        except Exception:
            _logger.exception("Task %s: failed to send task error alert", self.id)

    def _get_sale_order_delivery(self, sale_order):
        """Return the open delivery generated by the sale order."""
        self.ensure_one()
        pickings = sale_order.picking_ids.filtered(
            lambda p: p.picking_type_code == "outgoing" and p.state not in ("cancel", "done")
        )
        if pickings:
            return pickings.sorted(lambda p: (p.scheduled_date or p.create_date, p.id))[0]

        done_pickings = sale_order.picking_ids.filtered(
            lambda p: p.picking_type_code == "outgoing" and p.state == "done"
        )
        if done_pickings:
            return done_pickings.sorted(lambda p: (p.date_done or p.create_date, p.id))[-1]

        raise UserError(_("No delivery order was generated for Sale Order %s.") % sale_order.name)

    def _set_picking_done_quantities(self, picking):
        """Mark every sale-order delivery move as fully picked for Odoo 18."""
        for move in picking.move_ids.filtered(lambda m: m.state not in ("cancel", "done")):
            qty_done = move.product_uom_qty or 0.0
            if hasattr(move, "quantity"):
                move.quantity = qty_done
            elif hasattr(move, "quantity_done"):
                move.quantity_done = qty_done

            if hasattr(move, "picked"):
                move.picked = True

    def _validate_fulfillment_picking(self, picking):
        """Validate the trusted automated delivery and require Done state."""
        result = picking.with_context(skip_sms=True).button_validate()
        if picking.state != "done":
            action_model = result.get("res_model") if isinstance(result, dict) else False
            detail = _(" Odoo requested the %s wizard instead.") % action_model if action_model else ""
            raise UserError(
                _("Delivery %s did not reach Done after validation.%s")
                % (picking.name, detail)
            )
        return result

    def _mark_sale_order_paid(self, sale_order):
        """Create/post the customer invoice and register payment for paid online orders."""
        self.ensure_one()

        invoices = sale_order.invoice_ids.filtered(
            lambda move: move.move_type == "out_invoice" and move.state != "cancel"
        )
        if sale_order.invoice_status != "invoiced":
            invoices |= sale_order._create_invoices(final=True)

        invoices = invoices.filtered(lambda move: move.move_type == "out_invoice" and move.state != "cancel")
        if not invoices:
            raise UserError(_("No invoice could be created for Sale Order %s.") % sale_order.name)

        for invoice in invoices:
            if invoice.state == "draft":
                invoice.action_post()

        unpaid_invoices = invoices.filtered(
            lambda move: move.payment_state not in ("paid", "in_payment", "reversed")
            and move.amount_residual > 0
        )
        if not unpaid_invoices:
            return invoices

        journal = self.env["account.journal"].search(
            [
                ("type", "=", "bank"),
                ("company_id", "=", sale_order.company_id.id),
                ("active", "=", True),
            ],
            limit=1,
        )
        if not journal:
            journal = self.env["account.journal"].search(
                [
                    ("type", "=", "cash"),
                    ("company_id", "=", sale_order.company_id.id),
                    ("active", "=", True),
                ],
                limit=1,
            )
        if not journal:
            raise UserError(_("No active Bank or Cash journal found to mark %s paid.") % sale_order.name)

        register = self.env["account.payment.register"].with_context(
            active_model="account.move",
            active_ids=unpaid_invoices.ids,
        ).create({
            "journal_id": journal.id,
            "payment_date": fields.Date.context_today(self),
        })
        register.action_create_payments()
        return invoices

    def _verify_packing_delivery_coverage(self, sale):
        """Reject duplicate/extra deliveries before changing any stock quantity."""
        self.ensure_one()
        order = self.shopify_order_id
        products = order._packing_products()
        expected = {}
        for line in order.line_ids.filtered(lambda item: item.requires_shipping and item.quantity > 0):
            product_id = products[line.id].id
            expected[product_id] = expected.get(product_id, 0) + line.quantity
        pickings = sale.picking_ids.filtered(lambda picking: picking.picking_type_code == "outgoing" and picking.state != "cancel")
        if not pickings:
            raise UserError(_("The packed sale has no customer delivery."))
        warehouse_locations = self.env["stock.location"].search([("id", "child_of", order.packing_warehouse_id.view_location_id.id)])
        actual = {}
        for move in pickings.move_ids.filtered(lambda item: item.state != "cancel"):
            if move.company_id != order.company_id or move.location_id not in warehouse_locations or move.location_dest_id.usage != "customer":
                raise UserError(_("A delivery move is outside this packing company's warehouse or customer destination."))
            quantity = move.quantity if move.state == "done" else move.product_uom_qty
            quantity = move.product_uom._compute_quantity(quantity, move.product_id.uom_id)
            actual[move.product_id.id] = actual.get(move.product_id.id, 0) + quantity
        if set(actual) != set(expected) or any(float_compare(actual[product_id], quantity, precision_rounding=self.env["product.product"].browse(product_id).uom_id.rounding) != 0 for product_id, quantity in expected.items()):
            raise UserError(_("Existing done and open delivery quantities do not exactly cover the packed order. Supervisor reconciliation is required before any stock movement."))
        return True

    def _verify_completed_fulfillment_effects(self):
        """Read actual outcomes; a boolean flag alone never proves completion."""
        self.ensure_one()
        order = self.shopify_order_id
        sale = order.sale_order_id
        pickings = sale.picking_ids.filtered(lambda picking: picking.picking_type_code == "outgoing" and picking.state != "cancel")
        invoices = sale.invoice_ids.filtered(lambda invoice: invoice.move_type == "out_invoice" and invoice.state != "cancel")
        allowed_payments = ("paid", "in_payment") if order.completion_policy_version == "packing_v1" else ("paid", "in_payment", "reversed")
        if not sale or sale.company_id != order.company_id or not pickings or any(picking.state != "done" for picking in pickings) or not invoices or any(invoice.state != "posted" or invoice.payment_state not in allowed_payments or invoice.amount_residual > 0 for invoice in invoices):
            raise UserError(_("The inventory flag lacks verified completed delivery and accounting. Supervisor reconciliation is required."))
        if order.completion_policy_version == "packing_v1":
            if sale.warehouse_id != order.packing_warehouse_id:
                raise UserError(_("The verified sale order belongs to a different packing warehouse."))
            self._verify_packing_delivery_coverage(sale)
        return sale

    def _finalize_sale_delivery_accounting_strict(self):
        """Existing delivery/payment policy with failures propagated atomically.

        Used by both the task workflow and guarded label packing. The caller
        controls the transaction/savepoint and therefore never records partial
        delivery or accounting as success.
        """
        self.ensure_one()
        order = self.shopify_order_id
        if not order or not self.is_fulfillment_task:
            raise UserError(_("This task is not linked to a fulfillment order."))
        if self.fulfillment_inventory_deducted:
            return self._verify_completed_fulfillment_effects()
        sale = order._create_sale_order()
        if not sale:
            raise UserError(_("Sale order could not be created for %s.") % order.order_name)
        if sale.company_id != order.company_id:
            raise UserError(_("The sale order belongs to a different company."))
        if order.completion_policy_version == "packing_v1":
            products = order._packing_products()
            expected = {}
            for line in order.line_ids.filtered(lambda item: item.requires_shipping and item.quantity > 0):
                product_id = products[line.id].id
                expected[product_id] = expected.get(product_id, 0) + line.quantity
            actual = {}
            for line in sale.order_line.filtered(lambda item: not item.display_type and item.product_id.type != "service"):
                product_id = line.product_id.id
                quantity = line.product_uom._compute_quantity(line.product_uom_qty, line.product_id.uom_id)
                actual[product_id] = actual.get(product_id, 0) + quantity
            if actual != expected:
                raise UserError(_("The existing sale order's physical products or quantities do not match the packed order."))
            if sale.warehouse_id != order.packing_warehouse_id:
                raise UserError(_("The sale order warehouse does not match the packing warehouse."))
            self._verify_packing_delivery_coverage(sale)
        pickings = sale.picking_ids.filtered(lambda picking: picking.picking_type_code == "outgoing" and picking.state != "cancel")
        if not pickings:
            raise UserError(_("No delivery order was generated for Sale Order %s.") % sale.name)
        for picking in pickings.sorted("id"):
            if picking.state != "done":
                if picking.state == "draft":
                    picking.action_confirm()
                picking.action_assign()
                self._set_picking_done_quantities(picking)
                self._validate_fulfillment_picking(picking)
            if picking.state != "done":
                raise UserError(_("Delivery %s is not Done; invoicing was stopped.") % picking.name)
        invoices = self._mark_sale_order_paid(sale)
        if any(invoice.state != "posted" or invoice.payment_state not in (("paid", "in_payment") if order.completion_policy_version == "packing_v1" else ("paid", "in_payment", "reversed")) or invoice.amount_residual > 0 for invoice in invoices):
            raise UserError(_("Accounting has not confirmed posted, paid invoices for %s.") % sale.name)
        # Bounded private write after verifying actual delivery and accounting;
        # ordinary callers still cannot supply or forge this completion flag.
        self.sudo().write({"fulfillment_inventory_deducted": True})
        if order.fulfillment_type == "pickup":
            order.write({"state": "pickup_completed", "error_message": False})
        self.message_post(body=_("Sale Order %s delivered (%s) and marked paid (%s).") % (sale.name, ", ".join(pickings.mapped("name")), ", ".join(invoices.mapped("name"))))
        return sale

    def action_fulfillment_deduct_inventory(self):
        """Deduct inventory for the linked Shopify Order."""
        self.ensure_one()
        if not self.shopify_order_id or not self.is_fulfillment_task:
            return
            
        if self.shopify_order_id.completion_policy_version == "packing_v1":
            order = self.shopify_order_id
            order._packing_authorize(supervisor=True)
            order._packing_lock()
            order._packing_allocations()
            order._packing_refresh_eligibility()
            if any(shipment.packing_state != "packed" for shipment in order._packing_shipments()):
                raise UserError(_("Finish every box using its shipping label before completing this task."))
            return order._packing_finish_operational()

        if self.fulfillment_inventory_deducted:
            return

        try:
            risk_level = self.shopify_order_id._refresh_shopify_risk_level()
        except UserError as exc:
            message = str(exc)
            self.shopify_order_id.write({
                "state": "manual_required",
                "error_message": message,
            })
            self.message_post(body=message)
            return

        if risk_level in ("HIGH", "MEDIUM"):
            message = _(
                "Inventory deduction stopped because Shopify marked this order as %s risk. "
                "Manual review is required before fulfillment."
            ) % risk_level.title()
            self.shopify_order_id.write({
                "state": "manual_required",
                "error_message": message,
            })
            self.shopify_order_id._send_risk_notification()
            self.message_post(body=message)
            return

        _logger.info("Starting inventory deduction for task %s (Order: %s)", self.id, self.shopify_order_id.order_name)

        try:
            with self.env.cr.savepoint():
                self._finalize_sale_delivery_accounting_strict()

        except Exception as e:
            _logger.exception("Failed to fulfill sale order for task %s", self.id)
            if self.shopify_order_id.fulfillment_type == "pickup":
                self.shopify_order_id.write({
                    "state": "manual_required",
                    "error_message": str(e),
                })
            self.message_post(body=_("Failed to fulfill sale order: %s") % str(e))
            self._send_task_error_alert("Sale Order Fulfillment Failed", str(e))


    def unlink(self):
        if self.filtered(lambda task: task.is_fulfillment_task and task.shopify_order_id.completion_policy_version == "packing_v1"):
            raise UserError(_("Canonical packing tasks must be retained with their delivery and accounting history."))
        return super().unlink()

    @api.model_create_multi
    def create(self, vals_list):
        if "default_fulfillment_inventory_deducted" in self.env.context and not self.env.su:
            raise AccessError(_("Inventory completion cannot be supplied through task defaults."))
        for vals in vals_list:
            if "fulfillment_inventory_deducted" in vals and not self.env.su:
                raise AccessError(_("Inventory completion can only be set by the verified fulfillment finalizer."))
            effective_order_id = vals.get("shopify_order_id", self.env.context.get("default_shopify_order_id"))
            order = self.env["shopify.order"].browse(effective_order_id).exists() if effective_order_id else self.env["shopify.order"]
            if order and order.completion_policy_version == "packing_v1" and not self.env.su:
                raise AccessError(_("Packing tasks must be linked through the canonical order workflow."))
            if order and order.completion_policy_version == "packing_v1" and self._is_done_state(vals.get("state", self.env.context.get("default_state"))) and not (self.env.su and self.env.context.get("packing_internal_finalizer")):
                raise UserError(_("Create this fulfillment task as open; finish its boxes using their labels."))
        tasks = super().create(vals_list)
        for task in tasks:
            if task.is_fulfillment_task and task.shopify_order_id.completion_policy_version != "packing_v1" and self._is_done_state(task.state) and not task.fulfillment_inventory_deducted:
                try:
                    task.action_fulfillment_deduct_inventory()
                except Exception as e:
                    _logger.exception("Error in auto-deduct inventory on create")
                    task.message_post(body=_("Background error during inventory deduction: %s") % str(e))
                    task._send_task_error_alert("Inventory Auto-Deduct Failed (Create)", str(e))
        return tasks

    def write(self, vals):
        if "fulfillment_inventory_deducted" in vals and not self.env.su:
            raise AccessError(_("Inventory completion can only be set by the verified fulfillment finalizer."))
        if {"shopify_order_id", "is_fulfillment_task"}.intersection(vals):
            orders = self.mapped("shopify_order_id")
            if vals.get("shopify_order_id"):
                orders |= self.env["shopify.order"].browse(vals["shopify_order_id"])
            for order in orders.filtered(lambda record: record.completion_policy_version == "packing_v1"):
                if not self.env.su:
                    raise AccessError(_("Packing task links must be preserved by the canonical order workflow."))
                order._packing_lock()
                if order.packing_operational_state == "complete":
                    raise UserError(_("Completed packing task links must be retained."))
        restock_tasks = self.filtered("fulfillment_restock_item_id")
        restock_done_before = {t.id: t._restock_task_is_done() for t in restock_tasks}

        if "state" in vals and self._is_done_state(vals["state"]) and not (self.env.su and self.env.context.get("packing_internal_finalizer")):
            for task in self.filtered(lambda record: record.is_fulfillment_task and record.shopify_order_id.completion_policy_version == "packing_v1"):
                order = task.shopify_order_id
                order._packing_authorize()
                order._packing_lock()
                if order.packing_operational_state != "complete":
                    raise UserError(_("Complete each box through Scan to Finish or the Odoo Packing action. This task becomes Done after delivery and accounting succeed."))
        res = super().write(vals)
        # Check if task is being marked as done
        if 'state' in vals and self._is_done_state(vals["state"]):
             for task in self:
                  if task.is_fulfillment_task and task.shopify_order_id.completion_policy_version != "packing_v1" and not task.fulfillment_inventory_deducted:
                      try:
                          task.action_fulfillment_deduct_inventory()
                      except Exception as e:
                          # Don't block the write
                          _logger.exception("Error in auto-deduct inventory on write")
                          task.message_post(body=_("Background error during inventory deduction: %s") % str(e))
                          task._send_task_error_alert("Inventory Auto-Deduct Failed (Write)", str(e))

        for task in restock_tasks:
            try:
                if restock_done_before.get(task.id):
                    continue
                if not task._restock_task_is_done():
                    continue
                item_model = self.env["fulfillment.restock.item"].sudo()
                items = item_model.search([
                    ("todo_task_id", "=", task.id),
                    ("is_active_snapshot", "=", True),
                    ("inventory_transferred", "=", False),
                ])
                items |= item_model.search(
                    [("todo_task_id", "=", task.id)]
                    + item_model._shopify_reconciliation_domain()
                )
                if (
                    not items
                    and task.fulfillment_restock_item_id
                    and task.fulfillment_restock_item_id.is_active_snapshot
                    and not task.fulfillment_restock_item_id.inventory_transferred
                ):
                    items = task.fulfillment_restock_item_id
                if not items:
                    continue
                _logger.info(
                    "Restock task %s marked done; transferring inventory for items %s",
                    task.id, items.ids,
                )
                items.with_context(
                    transferred_by_uid=self.env.user.id
                ).sudo().action_transfer_inventory()
            except Exception:  # pylint: disable=broad-except
                _logger.exception(
                    "Failed to auto-transfer inventory for restock task %s", task.id
                )

        return res
